#!/bin/sh -eu
DATE=$(date +%F)
IS_DRAFT=0
OPEN_EDITOR=0

for arg in "$@"
do
	case $arg in
		-d|--draft)
		IS_DRAFT=1
		shift
		;;
		-e|--editor)
		OPEN_EDITOR=1
		shift
		;;
	esac
done

pwd
echo $DATE
read -r -p 'Enter a title: ' title
titleSlug=${title// /-}
if [ "$IS_DRAFT" == "1" ]
then
	newTitle="$titleSlug.md"
	p="./_drafts/$newTitle"
else
	newTitle="$DATE-$titleSlug.md"
	p="./_posts/$newTitle"
fi
echo $newTitle
cat << EOF > $p
---
title: $title
layout: post
---


EOF

if [ "$OPEN_EDITOR" == "1" ]
then
	echo "Would open editor"
	exit
	$EDITOR $p
fi