#!/bin/sh
DATE=$(date +%F)
DRAFTS_DIR="./_drafts/"
DEPLOY=0

for arg in "$@"
do
	case $arg in
		-D|--deploy)
		DEPLOY=1
		shift
		;;
	esac
done

echo $DATE
drafts=("$DRAFTS_DIR"*)

for i in "${!drafts[@]}"
do
	printf "%s) %s\n" "$i" "${drafts[$i]#"$DRAFTS_DIR"}"
done
printf "Select a draft from the above list: "
read -r opt

if [[ "$opt" =~ ^[0-9]+$ ]] && (( (opt >= 0) && (opt < "${#drafts[@]}") )); then
	true
else
	exit
fi
e="${drafts[$opt]}"
f="${e#"$DRAFTS_DIR"}"
newTitle=$DATE-$f

mv "$e" "./_posts/$newTitle"
echo "Published!"

git add "./_posts/$newTitle"
git commit -m "Publishing $newTitle"
git push

if [ "$DEPLOY" == "1" ]
then
	./contrib/deploy
fi

# https://stackoverflow.com/questions/16623835/remove-a-fixed-prefix-suffix-from-a-string-in-bash
# https://stackoverflow.com/questions/44862384/dynamically-generated-bash-menu
# https://stackoverflow.com/questions/21112707/check-if-a-string-matches-a-regex-in-bash-script