---
title: prplecake.com
description: prplecake.com
baseurl: ''
url: ''
markdown: kramdown
highlighter: rouge
lang: en
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-target-blank
- jekyll-sitemap
- nokogiri
paginate: 5
paginate_path: "/page/:num"
sass:
  style: compressed
target-blank:
  noreferrer: false
