baseURL = 'https://prplecake.com/'
languageCode = 'en-us'
title = 'prplecake.com'
enableRobotsTXT = true
theme = "gokarna"
defaultContentLanguage = "en"

[menu]
[[menu.main]]
# Unique identifiers are required for menu entries without a name property
# or for menu entries which re-use a name
identifier = "github"

# Absolute URL to external resource
url = "https://github.com/prplecake"
weight = 3

# Surround the menu entry (or name) with HTML content, such as Feather
# icons: https://feathericons.com
pre = "<span data-feather=\"github\"></span>"
post = ""
